#!/bin/bash
# src/git-integration/auto-commit.sh

# Auto-commit artifacts to git after each major decision

function commit_artifact() {
    local artifact_path=$1
    local stage=$2
    local decision=$3
    local confidence=${4:-MEDIUM}

    cd .kracked/KD_output/

    # Stage file
    git add "$artifact_path"

    # Create structured commit message
    git commit -m "[$stage] $decision

Generated by: Kracked_Skills v5.0.0
Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
Stage: $stage
Confidence: $confidence
Artifacts:
  - $artifact_path
"

    # Tag important milestones
    if [[ "$stage" == "Architecture" ]] || [[ "$stage" == "Release" ]]; then
        git tag -a "v${stage,,}-$(date +%s)" -m "Milestone: $stage complete"
    fi
}

# Example usage
# commit_artifact "architecture/system-design.md" "Architecture" "Microservices architecture approved" "HIGH"
